name: Deploy to Server

on:
  workflow_run:
    workflows: ["Docker Pipeline"]
    types:
      - completed
  workflow_dispatch:

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ github.event.repository.name }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
  APP_PORT: ${{ secrets.APP_PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Store SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master


    - name: SSH into server
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "sudo docker rmi -f $DOCKER_IMAGE:REPO-NAME:latest || true && sudo docker pull $DOCKER_IMAGE:$REPO_NAME-latest && sudo docker stop $REPO_NAME-container || true && sudo docker rm $REPO_NAME-container || true && sudo docker run -d --name $REPO_NAME-container -p $APP_PORT:8000 $DOCKER_IMAGE:$REPO_NAME-latest"
    
