name: Docker Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  PM2_PUBLIC_KEY: ${{ secrets.PM2_PUBLIC_KEY }}
  PM2_SECRET_KEY: ${{ secrets.PM2_SECRET_KEY }}
  PM2_MACHINE_NAME: ${{ secrets.PM2_MACHINE_NAME }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
  REPO_NAME: ${{ github.event.repository.name }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  NODE_ENV: ${{ secrets.NODE_ENV }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.REPO_NAME }}-latest
        build-args: |
          PM2_PUBLIC_KEY=${{ env.PM2_PUBLIC_KEY }}
          PM2_SECRET_KEY=${{ env.PM2_SECRET_KEY }}
          PM2_MACHINE_NAME=${{ env.PM2_MACHINE_NAME }}
          DB_NAME=${{ env.DB_NAME }}
          DB_USER=${{ env.DB_USER }}
          DB_PASSWORD=${{ env.DB_PASSWORD }}
          DB_HOST=${{ env.DB_HOST }}
          DB_PORT=${{ env.DB_PORT }}
          REDIS_HOST=${{ env.REDIS_HOST }}
          REDIS_PORT=${{ env.REDIS_PORT }}
          SECRET_KEY=${{ env.SECRET_KEY }}
          NODE_ENV=${{ env.NODE_ENV }}